### ISSUE TITLE
Some duplicate entries in Arabic browse lists

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#872] opened 2016-11-02 19:46 UTC
This is a long bug report with a lot of results from a series of tests I just ran.  My speculations as to why this is happening are in the final paragraph.  Sorry for my prolixity, but I wanted to document this!

http://syriaca.org/geo/browse.html?lang=ar&sort=%D9%82 duplicates the listing of http://syriaca.org/place/62 (actually, it occurs three times, once much farther down).  While the record includes several Arabic names, only one Arabic name is given in the two entries on the browse list.

Similarly http://syriaca.org/geo/browse.html?lang=ar&sort=%D8%AB duplicates the listing of http://syriaca.org/place/567

http://syriaca.org/geo/browse.html?lang=ar&sort=%D8%A7 also duplicates the listing of http://syriaca.org/place/484

http://syriaca.org/geo/browse.html?lang=ar&sort=%D8%A8&start=1&perpage=107 triplicates http://syriaca.org/place/42 and duplicates http://syriaca.org/place/299 , the latter of which also has a mention on the different browse list of http://syriaca.org/geo/browse.html?lang=ar&sort=%D9%85&start=1&perpage=60

http://syriaca.org/geo/browse.html?lang=ar&sort=%D8%B1 duplicates both http://syriaca.org/place/78 and http://syriaca.org/place/109, although not in the same order, as well as http://syriaca.org/place/172.  There is also an alphabetization issue here, as http://syriaca.org/place/27 should not precede http://syriaca.org/place/169 in Arabic alphabetization (although perhaps it does so due to a vowel letter, which should probably be stripped out before alphabetizing).

http://syriaca.org/geo/browse.html?lang=ar&sort=%D9%85 also has alphabetization issues and duplications: http://syriaca.org/place/138, http://syriaca.org/place/130, http://syriaca.org/place/501, and http://syriaca.org/place/125 (although you have to scroll to the very bottom - or find in "All results" page - to see its duplication).

All of these seem to have an Arabic name from Barsoum as well as one from Yaqut.  But oddly, http://syriaca.org/place/458 is not duplicated in the list at http://syriaca.org/geo/browse.html?lang=ar&sort=%D9%85 even though it has both a Yaqut Arabic name and a Barsoum Arabic name.  It does, however, also have a listing at http://syriaca.org/geo/browse.html?lang=ar&sort=%D9%83 .

Looking again at http://syriaca.org/place/62, it has five Arabic names, one starting with alif, one with ba', and three with qaf.  Checking the lists, I see that it occurs once in the alif browse list, once in the ba' browse list, and three times in the qaf browse list.  In every listing entry it appears with the same Arabic name (which is the one listed first in the record).  So it seems that the Arabic browse lists are being generated on the basis of all Arabic names (which may be the source of odd alphabetizations as well) rather than one Arabic name per place record, creating doublets.  But the content of each entry in the browse list is generated based on the first Arabic place name in the record (e.g. http://syriaca.org/place/299 in the "wrong" list http://syriaca.org/geo/browse.html?lang=ar&sort=%D9%85&start=1&perpage=60 on the basis of its third Arabic name).  This needs to be revisited, and probably discussed to identify which solution we are aiming for.

**Comment by wsalesky** [comment] 2016-11-02 20:03
@tacarlson I suspect you are correct. We create the browse on any Arabic name, but the display is on the first. I suspect poor planning on my part when I wrote the code.

We should discuss the desired behavior, before I make the corrections. We can continue to select the way we currently do, but correct the display so the correct name is selected. Or we can choose an Arabic name as a defacto "headword." 

Let me know what you think.

**Comment by davidamichelson** [comment] 2016-11-10 20:01
@wsalesky Thanks, I will discuss this with @nathangibson on Tuesday and we can report to you on Wed.

**Comment by nathangibson** [comment] 2016-11-14 17:59
If I may jump in as another curator of Arabic names ...

It seems to me as if we have 3 possible solutions:
 1. Automatically labeling one Arabic name as the headword. We could do this prioritized by source -- e.g., Yaqut takes precedence over Barsoum and so on. 
 2. Manually choosing an Arabic headword for each place/person that has multiple Arabic names (213 places and 2 persons by my count).
 3. Continuing to generate multiple listings for entities that have multiple Arabic names, but changing the name that is displayed to the one that is being alphabetized in each instance. 

This affects the Gazetteer way more than persons at this point. The first option above strikes me as the most practical, the main question for @tacarlson being whether prioritizing certain sources over others would yield decent results. 

Number 3 seems like it could be tricky for @wsalesky to implement.

**Comment by nathangibson** [comment] 2016-11-14 18:04
Also, I agree that http://syriaca.org/place/169 should be alphabetized before http://syriaca.org/place/27. Can't tell why it's not.

**Comment by nathangibson** [comment] 2016-11-14 18:07
@wsalesky In case it helps you run some tests, http://syriaca.org/place/27 should be alphabetized as رستن

**Comment by wsalesky** [comment] 2016-11-14 18:25
Thanks @nathangibson I will take a look. 

Also, I think I can change the display name to match the one being used for alphabetization, theoretically. I would just need to filter the name display selection to chose the Arabic name matching the browse parameter.  So don't count #3 out if that is the preferred option.

**Comment by tacarlson** [comment] 2016-11-14 19:23
The third option is slightly more difficult operationally, because there may be multiple Arabic names which match the browse parameter, as in several of the cases I cited at first.

I hope we will discuss this in a meeting tomorrow.

**Comment by nathangibson** [comment] 2016-11-15 17:59
OK @wsalesky , we've discussed this and for browse we'd like to try to do number 3. However, this will need some tweaking since some of the "alternate" names are very similar to each other and there's no reason for duplicates to show up right next to each other (for example, the two Arabic names for http://syriaca.org/place/567). 

A couple possible ways to filter out names that are too similar:
 1. Use Levenshtein distance. (Try a search for "Levenshtein distance in Arabic")
 2. Filter out any browse results in which the same item appears twice in a row. (Not a very clean solution in terms of MVC, but perhaps the most practical?)

Just FYI so it doesn't throw off your code, we may in fact designate Arabic headwords at some point in the future for other reasons. 

@tacarlson , @davidamichelson , @dlschwartz , @jsaintlauren  Did I miss anything?

**Comment by tacarlson** [comment] 2016-11-15 18:38
Alternately, to filter out names, we could give you a list of Unicode characters to ignore (e.g. vowels) and equivalencies, and you could filter out duplicates according to equivalencies.

This will probably require some testing and tweaking before deployment.

@nathangibson what is MVC?

**Comment by wsalesky** [comment] 2016-11-15 18:41
Hi all, I'm going through the comments now. @tacarlson I think this may be a good solution but need to run through the code once before I commit to a method. I will get back to you all tomorrow on feasibility. Thanks.

**Comment by tacarlson** [comment] 2016-11-15 19:00
Oh, is MVC https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller ?

**Comment by wsalesky** [comment] 2016-11-15 19:01
@tacarlson Yes, that is correct.

**Comment by tacarlson** [comment] 2016-11-15 19:01
Thanks!

**Comment by nathangibson** [comment] 2016-11-16 17:22
We're going to try ignoring certain unicode characters (as per @tacarlson 's suggestion above). I think I already gave you a list of these but if not let me know.

**Comment by nathangibson** [comment] 2016-11-16 17:54
Also, a good example of a place that should have two entries in different places on the page, see http://syriaca.org/place/42.html.

**Comment by wsalesky** [comment] 2016-12-07 17:01
@tacarlson @nathangibson How does this look? 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/geo/browse.html?lang=ar&sort=%D8%A7

**Comment by tacarlson** [comment] 2016-12-07 22:18
Thank you for working on this!  This is a lot closer!

A couple oddities remain:

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/place/295 has three Arabic names, two of which differ only by a vowel (so one of those should be suppressed), yet it occurs three times on http://wwwb.library.vanderbilt.edu/exist/apps/srophe/geo/browse.html?lang=ar&sort=%D8%A8 (twice together with two different Arabic names, which is fine, and then once three entries further down in the list, with the display name duplicating the former of the two earlier list entries.  See image, and compare the first and last Arabic name shown.
![image](https://cloud.githubusercontent.com/assets/3038894/20988672/5287d528-bc97-11e6-94cf-e0518372a58b.png)

Also, when an Arabic word within a name begins with the definite article string ال that string seems to be deleted from the name as displayed in the browse list.  Thus Bāb Allah (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/place/570) has the Arabic name باب الله, but it shows up in the browse list as باب له - that is, the definite article string has been deleted from the beginning of the second word in the name.  Cf. http://wwwb.library.vanderbilt.edu/exist/apps/srophe/place/557 and the first Arabic name of http://wwwb.library.vanderbilt.edu/exist/apps/srophe/place/486 .  For an instance where a single-word Arabic name which ought to have the definite article is displayed in the browse list without the definite article, see http://wwwb.library.vanderbilt.edu/exist/apps/srophe/place/283.  Arabic names that begin with the definite article should be displayed with the definite article (it's part of the name) but alphabetized as if the definite article were not there.  I suspect this is a variable reuse issue, removing the string for the purpose of alphabetizing (good) and then displaying the temporary name (with string removed) instead of displaying the correct name (with string present).  The displayed name should be the Arabic name of the record which gets alphabetized (ignoring the definite article) into this location in the list.

Let me know if this doesn't make sense.  I can do more testing later.

Thank you again!

**Comment by wsalesky** [comment] 2016-12-08 14:38
@tacarlson Thank you, that helps. I have added in the correct display name, will work on the correct filtering of duplicates.

**Comment by wsalesky** [comment] 2016-12-08 14:45
@nathangibson Perhaps you can help?
I thought I was filtering out vowels? Here is a simple test case using my current filters. It does not seem to do what I want. 

```
xquery version "3.0";
declare namespace tei="http://www.tei-c.org/ns/1.0";

let $titlestring := 'بارِمّا'
let $filtered := replace(replace(replace(replace($titlestring,'^\s+',''),'^(\sابن|\sإبن|\sبن)',''),'(ال|أل|ٱل)',''),'^[U064B - U0656]','')
return $filtered
```

**Comment by nathangibson** [comment] 2016-12-08 15:49
As best I can tell, there are two problems:
 1. We need to remove `^` from the unicode range at the end.
 2. For some reason eXide does not seem to recognize the unicode characters as unicode. It works if I insert the Arabic characters themselves, though you may not even be able to see them here:
```

xquery version "3.0";

let $titlestring := 'بارِمّا'
let $filtered := replace(replace(replace(replace($titlestring,'^\s+',''),'^(\sابن|\sإبن|\sبن)',''),'(ال|أل|ٱل)',''),'[ً-ٖ]','')
return $filtered

```

**Comment by nathangibson** [comment] 2017-03-30 09:20
Unfortunately the two issues in the above https://github.com/srophe/srophe-eXist-app/issues/872#issuecomment-270621737 are still there. Note the italicized edit I just made -- was maybe confusing before due to my typo!

**Comment by nathangibson** [comment] 2017-03-30 09:26
An additional issue is that place/78 is not appearing under browse for alif (http://wwwb.library.vanderbilt.edu/geo/browse.html?lang=ar&alpha-filter=%D8%A7) even though name78-12 (أَذاسا) should as far as I can tell. It does not begin with ال , which we are stripping out.

**Comment by wsalesky** [comment] 2017-04-03 00:55
@nathangibson 
place/78  is there, if you page through or use the 'all' option:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/geo/browse.html?lang=ar&alpha-filter=%D8%A7&start=1&perpage=50

I tested the new filter it seems to work, so all we have left is the back-to-back repetition error. Thanks for reviewing.

**Comment by tacarlson** [comment] 2017-04-03 02:07
It is true that place/78 appears in the list under the name اورفه but not under the name أَذاسا , probably because the initial alif has a hamza on top of it.  In order to have a robust Arabic browse, U+0622, U+0623, and U+0625 should all be alphabetized as if U+0627 (plain alif).

________________________________

**Comment by nathangibson** [comment] 2017-04-03 13:22
Hmm, now it appears to be fixed?! (Place/78 appears under أَذاسا on http://wwwb.library.vanderbilt.edu/exist/apps/srophe/geo/browse.html?lang=ar&alpha-filter=%D8%A7&start=1&perpage=50).

**Comment by wsalesky** [comment] 2017-04-03 13:33
@tacarlson thanks for the clarification. We were filtering the the name  أَذاسا out  unintentionally due to the filter on: 

`replace('^(\sابن|\sإبن|\sال|أل|ٱل''),'')`

I'm still investigating this, I thought this was just the sort order, not the filter (i.e. if it gets pulled into the letter browse or not).

**Comment by wsalesky** [comment] 2017-04-03 13:34
@nathangibson I added the following:
`replace(replace(replace(replace(replace(replace($titlestring,'^\s+',''),'آ|إ|أ','ا'),'^(\sابن|\sإبن|\sبن)',''),'(ال|أل|ٱل)',''),'[ً-ٖ]',''),'[U064B-U0656]','')`

Wondering if it will have unintended consequences... Let me know if you see an issues.

**Comment by wsalesky** [comment] 2017-04-03 13:43
Also, I can not reasonably remove back-to-back records with the current logic we use. We can discuss more at our next meeting if this is a real display concern.

**Comment by nathangibson** [comment] 2017-04-03 14:19
Let me comment this up to see if I catch anything:

```
replace(
  replace(
    replace(
      replace(
        replace(
          replace($titlestring,'^\s+',''), //remove leading spaces. [1]
        'آ|إ|أ','ا'), //normalize letter alif (ا). [2]
      '^(\sابن|\sإبن|\sبن)',''), //remove all forms of (ابن) with leading space [3]
    '(ال|أل|ٱل)',''), //remove all definite articles [4]
  '[ً-ٖ]',''), //remove vowels and diacritics [5]
'[U064B-U0656]','') //remove vowels and diacritics [6]
```
5. and 6. appear to be exactly the same. 

As far as I can tell, it would work best to switch the order to the following: 1, 5 or 6, 4, 2, 3. My reason for this is that removing vowels/diacritics first may help make sure that the other replacements are processed correctly. But 4 should come before 2 because we want 4 to catch only the definite article, and normalizing the alif (2) might make it catch more than that. 3 should come last to make sure it still works if there are any weird diacritics or alifs on it. 

If we use the order I've suggested, then I would also suggest adding U0671 (ٱ) to the alif normalization. Thus 'آ|إ|أ' would become 'آ|إ|أ|ٱ'. 

For the step that is currently n. 3 (remove all forms of (ابن) with leading space), I would suggest also requiring a trailing space to exclude the other words (rare) that begin this way. Thus: '^(\sابن|\sإبن|\sبن)' should be '^(\sابن|\sإبن|\sبن)\s','\s'). 

@tacarlson regarding n. 3, did we decide to disregard ابن in names that *start* with it? (I'm trying to account for the ^ at the beginning.) For example, shouldn't Ibn Khaldun be alphabetized under "Ibn" rather than "Khaldun"?

@wsalesky I would also suggest we change n. 4 to require a leading space or the beginning of string -- it could currently match something in the middle of a word, right? So '(ال|أل|ٱل)' should be '(^|\s)(ال|أل|ٱل)','\1'.

Finally, you could perhaps include a comment in your code that this normalizes for alphabetization the most common cases, but that if app data uses rare Arabic glyphs such as those in the range U0674-U06FF, further normalization may be needed.

**Comment by nathangibson** [comment] 2017-04-03 14:20
I don't consider back to back records a major issue. It's OK with me if we drop it, but let's get everyone's opinion at the meeting.

**Comment by wsalesky** [comment] 2017-04-03 14:37
@nathangibson Thank you! This is exactly what I needed. I was getting a bit tangled up in the different steps. I will try rewriting as you suggested and we can run a test.

**Comment by wsalesky** [comment] 2017-04-03 15:00
@nathangibson How does it look now?

**Comment by nathangibson** [comment] 2017-04-03 15:19
Is this being applied yet to persons, e.g. http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/browse.html?lang=ar&alpha-filter=%D8%A7&start=1&perpage=206 ? 

I went to persons to check the alphabetization of ابن and found a good test case. I'm seeing the following order: person/236, person/271, person/1021, person/224. The order should be person/1021, person/224, person/271, person/236. It looks like in that case neither ال (definite article) nor ابن is being ignored. And none of those should be on the ا page because they start with ب once the ال is removed. So if you have already applied the code to persons, then something isn't working right. If you haven't this is a good test case to see if they shape up :-)

**Comment by wsalesky** [comment] 2017-04-03 15:21
@nathangibson sadly it is applied to persons. I will do some debugging to see if I can figure out what is going on.

**Comment by wsalesky** [comment] 2017-04-03 18:17
@nathangibson the script currently removes all forms of (ابن) with leading space. I think this is where the problem is, there does not seem to be a space in these names? Correct?

**Comment by nathangibson** [comment] 2017-04-04 12:17
@wsalesky Ahh, there is a space, but the regex also says it should be the *beginning* of the string `'^(\sابن|\sإبن|\sبن)'`, right? So that's why it's not catching ابن in البطريرك يوحنا ***ابن*** المعدني

In fact it is probably not catching anything right now because the ones at the beginning don't have a space and the ones with a space are not at the beginning.

But I'm confused regarding in which cases we wanted to disregard ابن anyway (sorry!). As best I can tell, this comes from a comment by @tacarlson  https://github.com/srophe/srophe-eXist-app/issues/26#issuecomment-217076723. Do we want to ignore it in the middle or at the beginning? I'll try to get clarification from @tacarlson .

In any case, there's also something up with ال because if it were correctly disregarded these would be in a different order and on the ب page instead.

**Comment by wsalesky** [comment] 2017-04-04 13:22
@nathangibson Hum, a `'^\s'` snuck into my code ahead of the  ال I have removed it (changed it to ` '^(ال|أل|ٱل)'`). Does that look better re: ال ?

**Comment by nathangibson** [comment] 2017-04-05 12:44
@wsalesky That does seem to correctly sort initial ال and place entries beginning with ال on the correct page. I would suggest using `'(^|\s)(ال|أل|ٱل)'` so that it also ignores word-initial ال for words that aren't the first word. This would, for example, correctly put person/271 before person/236 on http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/browse.html?lang=ar&alpha-filter=%D8%A8&start=1&perpage=46. But this is a very minor issue as in any entries that have the same first word will be close together and thus easy to find.

**Comment by wsalesky** [comment] 2017-04-05 14:06
Done!

**Comment by nathangibson** [comment] 2017-04-11 09:01
Great! 
ال looks like it is sorting correctly now. 
Can we change '^(\sابن|\sإبن|\sبن)' to '^(ابن|إبن|بن)' and then I think we should be done (fingers crossed) and you can close the issue?

**Comment by wsalesky** [comment] 2017-04-12 13:12
Done. If it looks right you can close this.

**Closed** 2017-06-13 17:40 UTC
Labels: bug, gazetteer

**Comment by nathangibson** [comment] 2017-06-14 10:16
Thanks!
