### ISSUE TITLE
Works commemorated in works

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-eXist-app#912] opened 2016-12-16 17:17 UTC
In the relationships box on the work page of BHSE, it looks like the work itself is listed as a "person commemorated." See for example work/804 where the text Mary and Euphemia is listed as a person commemorated in the text Mary and Euphemia.

**Comment by wsalesky** [comment] 2016-12-19 03:18
Fixed on dev, will need to fix on production.
Note to self: Issue seems to be caused by new range index. 

```
<create qname="tei:TEI">
                <field name="uri" match="//tei:publicationStmt/tei:idno" type="xs:string">
                    <field name="uriType" match="@type" type="xs:string"/>
                </field>
                <field name="title" match="//tei:titleStmt/tei:title" type="xs:string"/>
            </create>
```

This causes problems when transversing the tree structure to get to just a regular idno. (returns the full TEI record.)

**Comment by wsalesky** [comment] 2016-12-19 23:04
Fixed on Prod and Dev.

**Closed by wsalesky** 2016-12-19 23:04 UTC
Labels: bug
