### ISSUE TITLE
Bug in Works Cited module

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-eXist-app#888] opened 2016-11-12 19:38 UTC
The "Preferred Citation" box of http://syriaca.org/bibl/670 reads:

> Brooks, E. W., ed. "Letters I to LXI." In A Collection of Letters of Severus of Antioch, from Numerous Syriac Manuscripts, E. W. Brooks, ed., , Patrologia Orientalis, tomus 12 (Paris: Firmin-Didot et cie, 1919-1920Paris: Firmin-Didot et cie, 1919) Tomus Duodecimus, R. Graffin and F. Nau, eds., , , Patrologia Orientalis, tomus 12 (Paris: Firmin-Didot et cie, 1919-1920Paris: Firmin-Didot et cie, 1919).

Notice in particular the quadruple appearance of the string "Paris: Firmin-Didot et cie, 1919" in addition to the double and triple commas.

**Comment by tacarlson** [comment] 2016-11-12 19:40
There is also a missing space before "Severus" in the "Publication Title" below:
"A Collection of Letters ofSeverus of Antioch, from Numerous Syriac Manuscripts"

**Comment by nathangibson** [comment] 2016-11-14 15:39
Thanks for noticing this @tacarlson .

@wsalesky , I think we should pause on the visualization issues for this while we sort out among the editors what the correct data format for this is. 

@dlschwartz and @davidamichelson , this was a record we discussed earlier and came up with a format that did not envision Zotero being a part of our workflow. Something like this in its current format would be impossible to import into or edit in Zotero. I'll post here a suggested revision of something that might work better. @tacarlson and @jsaintlauren your input is of course also welcome if you're interested in this issue.

**Comment by nathangibson** [comment] 2016-11-14 17:15
OK, folks, what do you think about this? 

https://github.com/srophe/srophe-app-data/blob/dev/data/bibl/tei/670.xml

Here's the situation: This bibl record is supposed to represent part 1 (so-called "Fasc. I") of a two-part edition by Brooks of the Letters of Severus in volume 12, fasc. II of Patrologia Orientalis. The problem is how to represent the two "monogr" level works of which this is a part:
 1. The two parts of the Letters of Severus (a single conceptual unit) 
 2. The volume of Patrologia Orientalis in which part 1 appears. (Part 2 appears in a different volume.)

What we originally came up with, which you can see on the master tree, is to use two monogr elements, one for each of the above. That worked well conceptually, but causes some practical issues:
 1. Tweaking the stylesheet to correctly convert it to a citation on the HTML page seems exceedingly complex.
 2. It definitely cannot be modeled in Zotero, where we want to do our bibl editing. 

My suggestion is to dispense with the conceptual entity (and the URI http://syriaca.org/bibl/677) for monogr 1 above. Instead, for items like this we could put label each part using the title of its parent item plus the title (or number) of the part, thus: "A Collection of Letters of Severus of Antioch, from Numerous Syriac Manuscripts: **Letters I to LXI**". (Alas, analytic does not allow biblScope, so we can't put the part number/title in a biblScope.) 

I was tempted in a case like this where the monogr-level title is merely a number ("Tomus Duodecimus") to simply represent this either as a multi-volume book or as a journal. (Thus the monogr would become "Patrologia Orientalis.") But this would make all of PO (or similar publications) one big monogr with no good way to maintain separate editors for each volume. So I have nothing better to offer as a title than "Tomus Duodecimus." 

In the format I've drafted, I think essentially everything can be entered using Zotero, except the custom units "tomus" and "fasc." I know @dlschwartz was particular about preserving those. But unless we do a workaround in Zotero, I think the best we can do is putting "12.2" as the series number. And I think the format is quite functional for providing the information people need to find the item. 

The only thing we lose functionally is the link between the two parts of the letters of Severus. I don't know anything to do about that, unless we want to work out a way to use Zotero's "Related" feature and export it to TEI. 

As far as visualization, the new format also takes care of most of the issues. Compare
http://wwwb.library.vanderbilt.edu/bibl/670 to http://syriaca.org/bibl/670. The main remaining issue is that the pages aren't included in the citation for some reason. 

Sorry this turned into a tome! But I think these are some issues we have to sort out before we can start pushing Zotero records directly to the Works Cited module.

**Comment by nathangibson** [comment] 2016-11-15 16:46
Note from 11/15 meeting: 
For something like this, we could put a note like "series number = tomus" in case Zotero supports this in the future.

**Comment by nathangibson** [comment] 2016-11-15 16:49
@wsalesky Now we can discuss visualization for this. The main thing I see at this point is that the pages aren't showing up -- I can't tell why.

**Comment by wsalesky** [comment] 2016-11-15 19:03
Thanks @nathangibson I will take a look.

**Comment by wsalesky** [comment] 2016-11-15 19:11
Thank you! For some reason I could not see that it was the biblScope that was missing. 
How does this look: 
http://wwwb.library.vanderbilt.edu/bibl/670

**Comment by nathangibson** [comment] 2016-11-15 20:19
Thanks @wsalesky ! Looks good to me. I think we can close this.

**Closed by nathangibson** 2016-11-15 20:19 UTC
Labels: bibl module, bug
